---
- hosts: all
  sudo: true
 
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install nginx
      apt: name=nginx state=present
    - name: Copy across new virtual host
      template:
        src=nginx.conf
        dest=/etc/nginx/nginx.conf
